name: PHP CI CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install dependencies
      run: composer install
      
    - name: Build
      run: composer dump-autoload -o

    - name: Deploy to Production Server
      uses: appleboy/scp-action@master
      env: 
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.privateKey }}
      with:
        source: "./*.php,lib,vendor" 
        target: "/var/www/html/wordpress/wp-content/plugins/bike-sharing-plugin/"
        overwrite: true
